---
title: "ro_split"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Things Needed

```{r}

# read in host_names, rarefied_physeqs

readRDS("../intermediate_files/rds/host_names.rds")
readRDS("../intermediate_files/rds/rarefied_physeqs.rds")

```

## Isolate RO plots and remove empty taxa

```{r}

# rarefied_physeqs is a list with rarefied root physeqs and unrarefied soil physeq

ro_physeqs <- list()

for (a_host in host_names) {
  ro <- subset_samples(rarefied_physeqs[[a_host]], 
                 grepl("RO", sample_names(rarefied_physeqs[[a_host]])))
  ro_physeqs[[a_host]] <- prune_taxa(taxa_sums(ro) > 0, ro)
}

```

## Condense individual OTU tables into a single column (merge plots)

```{r}

# function to make a single column matrix
make_matrix <- function(physeq) {
  single_col_matrix <- as(colSums(otu_table(physeq)), "matrix")
  return(single_col_matrix)
}


ro_mats <- lapply(ro_physeqs, make_matrix)

# name the columns by host
for (a_host in host_names) {
  colnames(ro_mats[[a_host]]) <- a_host
}


```
## Merge the columns into one OTU table

```{r}

# Not a great solution! But it's the only one I could come up with
# merge() only takes two inputs at a time and we had problems with Reduce()

# merge the first two host columns by ASV names
r <- merge(ro_mats$`Koa root`, ro_mats$`Olapa root`, by="row.names", all=TRUE)
# ASVs become a row, change back to rownames
rownames(r) <- r[,1]
# remove the column where the ASVs just were so the next merge works
r[,1] <- NULL

# merge the remaining 5 columns to the 2-column matrix
for (i in 3:7) {
  r <- merge(r, ro_mats[[i]], by="row.names", all=T)
  rownames(r) <- r[,1]
  r[,1] <- NULL
}

# somewhere in there it became a data frame, so turn back into matrix and rename
ro_full_mat <- as(r, "matrix")

# Changes NAs to 0
ro_full_mat[is.na(ro_full_mat)] <- 0

# save for later
saveRDS(ro_full_mat, "../intermediate_files/rds/ro_full_mat.rds")
write.csv(ro_full_mat, "../intermediate_files/csv/ro_full_mat.csv")

```


## make presence absence matrix

```{r}

# make copy of abundance matrix for presence absence
ro_full_mat_pa <- ro_full_mat

# makes presence absence (turns any value > 0 into 1)
ro_full_mat_pa[ro_full_mat_pa > 0] <- 1

# save for later
saveRDS(ro_full_mat_pa, "../intermediate_files/rds/ro_full_mat_pa.rds")
write.csv(ro_full_mat_pa, "../intermediate_files/csv/ro_full_mat_pa.csv")

```


## Upset Plot

```{r}

library(ComplexUpset)
library(ggplot2)

# upset wants a data frame
ro_full_df_upset <- as.data.frame(ro_full_mat_pa)


# Generate upset plot with percentage labels
# change min_size to only show intersections >1%
ro_upset <- 
  upset(
  ro_full_df_upset, 
  host_names, 
  name = '',
  min_size=11,
  width_ratio = 0.2,
  wrap = TRUE,
  base_annotations = list(
    'Intersection size'=intersection_size(
      text=list(size=3, vjust=-0.5), 
      text_aes = aes(
      label=paste0(signif(intersection_size/nrow(ro_full_mat_pa) * 100, digits=2), '%')))), 
  themes = upset_modify_themes(
    list(
        'Intersection size'=theme(
          panel.grid.major=element_blank(), 
          panel.grid.minor=element_blank(),
          plot.margin = unit(c(1,1,1,1), "cm"),
          axis.line = element_line(colour="gray"))
      )
    )
  ) + ggtitle('B) Remnant Forest')

library(patchwork)
pdf("figures/upset-test.pdf", width = 10, height=10)
(ak_upset | ro_upset) + plot_layout(ncol=1, nrow=2)
dev.off()

# includes all intersections
ro_upset_full <- 
  upset(
  ro_full_df_upset, 
  host_names, 
  name = '',
  min_size=1,
  width_ratio = 0.1,
  wrap = TRUE,
  base_annotations = list(
    'Intersection size'=intersection_size(
      text=list(size=3, vjust=-0.1, hjust=0, angle=60), 
      text_aes = aes(
      label=paste0(signif(intersection_size/nrow(ro_full_mat_pa) * 100, digits=2), '%')))), 
  themes = upset_modify_themes(
    list(
        'Intersection size'=theme(
          panel.grid.major=element_blank(), 
          panel.grid.minor=element_blank(),
          axis.line = element_line(colour="gray"))
      )
    )
  ) + ggtitle('Remnant Forest')

```


## RO Nestedness

```{r}

# Make a copy of presence absence matrix for nestedness
ro_full_mat_nest <- as(ro_full_mat_pa, "matrix")

# Tranpose matrix so that ASVs are columns and hosts are rows
ro_full_mat_nest <- t(ro_full_mat_nest)

# ordered by visually assessing nestedness, not by size
ro_sample_order <- c("Soil",
                     "Koa root",
                     "roala root",
                     "Grass root",
                    "Kolea root",
                    "Ohia root",
                    "Olapa root")

ro_full_mat_nest <- ro_full_mat_nest[ro_sample_order,]



# count how many samples each ASV is in
ro_spread_scores <- colSums(ro_nest_mat)

# assign each ASV a weighted score based on its presence in different sample types
# lower sample types get a higher score to give figure a right-aligned nested structure
ro_rank_scores <- apply(ro_nest_mat, MARGIN=2, function(x) sum(x * rev(seq_along(x))))

ro_composite_score <- data.table(OTU_ID = names(ro_spread_scores),
                              spread_score = ro_spread_scores,
                              rank_score = ro_rank_scores)

ro_composite_score <- ro_composite_score[order(rank_score, spread_score)]

ro_asv_order <- ro_composite_score$OTU_ID

ro_full_mat_nest <- ro_full_mat_nest[, ro_asv_order]

ro_nest_plot <- heatmap(ro_nest_mat, Colv=NA, Rowv=NA, labCol=NA, margins = c(5,5))

```



