---
title: "ak_bar_shared"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Libraries

```{r}

library(tibble)
library(dplyr)

```

## Things Needed

```{r}

# matrix of ASV counts by host
readRDS("../intermediate_files/ak_full_mat.rds")

# taxonomy table from full physeq object 
readRDS("../intermediate_files/full_tax_table_df.rds")

# a vector of our host names
readRDS("../intermediate_files/host_names.rds")


```

## Data Housekeeping

```{r}

# rename and convert to data frame
ak_barplot_df <- as.data.frame(ak_full_mat)

# format taxonomy table
full_tax_table_df <- full_tax_table_df %>% rownames_to_column("ASV")

# where family = Paraglomerales, change to Glomeromycotina
# Paraglomerales is an order, not a family. Issue stems from NCBI taxonomy.
full_tax_table_df$Family <- gsub("Paraglomerales", "Glomeromycotina", full_tax_table_df$Family)

```


## Isolate ASVs shared by all hosts

```{r}

ak_shared_asvs <- list()

for (a_host in host_names) {
  # subset shared ASVs. 
  # this code removes rows with any zero value
  # all() asks "are all values true?" and apply does this to all rows
  ak_shared <- ak_barplot_df[apply(ak_barplot_df, 1, function(row) all(row!=0)),]
  # make asv rownames into a column
  ak_shared <- rownames_to_column(ak_shared, "ASV")
  # make a new df with asv names and host sample asv counts as columns
  ak_shared <- select(ak_shared, ASV, a_host)
  # take sum of all unique host sample sequences
  total_host_sum <- sum(ak_barplot_df[[a_host]])
  # make new relative abundance column by dividing unique count by total
  ak_shared <- mutate(ak_shared, rel_abun=((ak_shared[[a_host]] / total_host_sum) * 100))
  # make new column taking family from tax_table where asv names match in both dfs
  ak_shared$Family <- full_tax_table_df$Family[match(ak_shared$ASV, full_tax_table_df$ASV)]
  # make new column with host name filling all cells
  ak_shared$Host <- rep(a_host, nrow(ak_shared))
  # change host colname for future rbind
  colnames(ak_shared)[2] <- "Count"
  # save resulting df in our list
  ak_shared_asvs[[a_host]] <- ak_shared
}

```

## rbind

```{r}

ak_total_shared_rbind <- do.call("rbind", ak_shared_asvs)

saveRDS(ak_total_shared_rbind, "../intermediate_files/ak_total_shared_rbind.rds")
write.csv(ak_total_shared_rbind, "../intermediate_files/ak_total_shared_rbind.csv")

```

## Plot

```{r}
library(ggplot2)

ak_shared_bar <- ggplot(ak_total_shared_rbind, aes(x=Host, fill=Family, y=rel_abun)) +
  geom_bar(stat="identity", position="stack") +
  theme(axis.text.x = element_text(angle=90, size=14, colour="black", vjust=0.5, hjust=1, face="bold"), panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.background=element_blank(),
        axis.line = element_line(colour="gray"),
        axis.title.y = element_text(size=16, face="bold"),
        legend.title = element_text(size=16, face="bold"),
        legend.text = element_text(size=12, face="bold", colour="black"),
        axis.text.y = element_text(colour="black", size=12, face="bold")) +
  ylim(0,100) +
  theme(plot.margin = unit(c(1,1,1,1), "cm")) +
  labs(x = "", y = "Relative Abundance (%)", fill="Family") +
  #match colors to unique plot
  scale_fill_manual(values = c("Acaulosporaceae" = "#9e0142",
                               "Ambisporaceae" = "#d53e4f",
                               "Archaeosporaceae" = "#f46d43",
                               "Claroideoglomeraceae" = "#fdae61",
                               "Gigasporaceae" = "#e6f598",
                               "Glomeraceae" = "#abdda4",
                               "Glomeromycotina" = "#66c2a5",
                               "Paraglomeraceae" = "#3288bd"))

```




