---
title: "ak_split"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Take rarefied root physeq objects + soil object.
Use subset_samples to keep only AK or RO plots.

## AK Restored

```{r}

ak_soil <- subset_samples(merged_soil_plot, grepl("AK", sample_names(merged_soil_plot)))
ak_soil <- prune_taxa(taxa_sums(ak_soil) > 0, ak_soil)

ak_koa <- subset_samples(rarefied_koa, grepl("AK", sample_names(rarefied_koa)))
ak_koa <- prune_taxa(taxa_sums(ak_koa) > 0, ak_koa)

ak_kolea <- subset_samples(rarefied_kolea, grepl("AK", sample_names(rarefied_kolea)))
ak_kolea <- prune_taxa(taxa_sums(ak_kolea) > 0, ak_kolea)

ak_ohia <- subset_samples(rarefied_ohia, grepl("AK", sample_names(rarefied_ohia)))
ak_ohia <- prune_taxa(taxa_sums(ak_ohia) > 0, ak_ohia)

ak_olapa <- subset_samples(rarefied_olapa, grepl("AK", sample_names(rarefied_olapa)))
ak_olapa <- prune_taxa(taxa_sums(ak_olapa) > 0, ak_olapa)

ak_akala <- subset_samples(rarefied_akala, grepl("AK", sample_names(rarefied_akala)))
ak_akala <- prune_taxa(taxa_sums(ak_akala) > 0, ak_akala)

#ak_pilo <- subset_samples(rarefied_pilo, grepl("AK", sample_names(rarefied_pilo)))
#ak_pilo <- prune_taxa(taxa_sums(ak_pilo) > 0, ak_pilo)

ak_grass <- subset_samples(rarefied_grass, grepl("AK", sample_names(rarefied_grass)))
ak_grass <- prune_taxa(taxa_sums(ak_grass) > 0, ak_grass)



```


```{r}

# function to make a single column matrix
make_matrix <- function(physeq) {
  single_col_matrix <- as(colSums(otu_table(physeq)), "matrix")
  return(single_col_matrix)
}

```



```{r}

ak_soil_mat <- make_matrix(ak_soil)
ak_koa_mat <- make_matrix(ak_koa)
ak_kolea_mat <- make_matrix(ak_kolea)
ak_ohia_mat <- make_matrix(ak_ohia)
ak_olapa_mat <- make_matrix(ak_olapa)
ak_akala_mat <- make_matrix(ak_akala)
#ak_pilo_mat <- make_matrix(ak_pilo)
ak_grass_mat <- make_matrix(ak_grass)


```


```{r}

# Change the column name
colnames(ak_soil_mat) <- c("Soil")

colnames(ak_koa_mat) <- c("Koa root")

colnames(ak_ohia_mat) <- c("Ohia root")

colnames(ak_olapa_mat) <- c("Olapa root")

colnames(ak_kolea_mat) <- c("Kolea root")

colnames(ak_akala_mat) <- c("Akala root")

#colnames(ak_pilo_mat) <- c("Pilo root")

colnames(ak_grass_mat) <- c("Grass root")


```


```{r}

# merge 2 matrices by row names
# all=TRUE adds extra columns or rows with an NA where there is no matching value
# The result is a 3 column matrix with the first column as all the ASV names
ak_sk_mat <- merge(ak_soil_mat, ak_koa_mat, by="row.names", all=TRUE)

# Takes ASV names fakm column 1 and names rows after them 
rownames(ak_sk_mat) <- ak_sk_mat[,1]

# Removes column 1 with ASV names
ak_sk_mat[,1] <- NULL

#Add ohia
ak_sko_mat <- merge(ak_sk_mat, ak_ohia_mat, by="row.names", all=T)
rownames(ak_sko_mat) <- ak_sko_mat[,1]
ak_sko_mat[,1] <- NULL

#Add olapa
ak_skoo_mat <- merge(ak_sko_mat, ak_olapa_mat, by="row.names", all=T)
rownames(ak_skoo_mat) <- ak_skoo_mat[,1]
ak_skoo_mat[,1] <- NULL

#Add kolea
ak_skook_mat <- merge(ak_skoo_mat, ak_kolea_mat, by="row.names", all=T)
rownames(ak_skook_mat) <- ak_skook_mat[,1]
ak_skook_mat[,1] <- NULL

#Add akala
ak_skooka_mat <- merge(ak_skook_mat, ak_akala_mat, by="row.names", all=T)
rownames(ak_skooka_mat) <- ak_skooka_mat[,1]
ak_skooka_mat[,1] <- NULL

#Add pilo
#ak_skookap_mat <- merge(ak_skooka_mat, ak_pilo_mat, by="row.names", all=T)
#rownames(ak_skookap_mat) <- ak_skookap_mat[,1]
#ak_skookap_mat[,1] <- NULL

#Add grass
ak_skookag_mat <- merge(ak_skooka_mat, ak_grass_mat, by="row.names", all=T)
rownames(ak_skookag_mat) <- ak_skookag_mat[,1]
ak_skookag_mat[,1] <- NULL


#ak_skookapg_mat$`Pilo root` <- NULL
#ak_skookag_mat <- ak_skookapg_mat

# Changes NAs to 0
ak_skookag_mat[is.na(ak_skookag_mat)] <- 0

```


## Make presence absence matrix

```{r}

# make copy of abundance matrix for presence absence
ak_skookag_mat_pa <- ak_skookag_mat

# Makes presence absence (turns any value > 0 into 1)
ak_skookag_mat_pa[ak_skookag_mat_pa > 0] <- 1


```




```{r}

library(ComplexUpset)

# make a copy of presence absence matrix
ak_skookag_boo <- ak_skookag_mat_pa

# convert binary to boolean
ak_skookag_boo <- apply(ak_skookag_boo, 2, function(x) as.logical(x))

# convert matrix to data frame 
ak_skookag_boo <- as.data.frame(ak_skookag_boo)

# extract col names to feed into upset
ak_skookag_hosts <- colnames(ak_skookag_boo)


# Generate upset plot with percentage labels
ak_upset <- 
  upset(
  ak_skookag_boo, 
  ak_skookag_hosts, 
  name = '',
  min_size=1,
  width_ratio = 0.1,
  base_annotations = list(
    'Intersection size'=intersection_size(
      text=list(size=3, vjust=-0.1, hjust=0, angle=60), 
      text_aes = aes(
      label=paste0(signif(intersection_size/nrow(ak_skookag_boo) * 100, digits=2), '%')))), 
  themes = upset_modify_themes(
    list(
        'Intersection size'=theme(
          panel.grid.major=element_blank(), 
          panel.grid.minor=element_blank(),
          axis.line = element_line(colour="gray"))
      )
    )
  )



```





```{r}

# old upset code (using UpSetR)
upset(ak_skookag_mat_pa, nsets=7, nintersects = NA, sets.x.label = "Total ASVs")

```



## AK Nestedness

```{r}

# Convert data frame to matrix
ak_skookag_mat_nest <- as(ak_skookag_mat_pa, "matrix")


# Tranpose matrix (flip axes)
ak_skookag_mat_nest <- t(ak_skookag_mat_nest)


# Ordered by what looks to be more nested visually (not by size)
alt_ak_sample_order <- c("Soil",
                     "Grass root",
                     "Akala root",
                     "Koa root",
                    "Olapa root",
                    "Ohia root",
                    "Kolea root")

alt_ak_nest_mat <- ak_skookag_mat_nest[alt_ak_sample_order,]



# count how many samples each ASV is in
alt_ak_spread_scores <- colSums(alt_ak_nest_mat)

# assign each ASV a weighted score based on its presence in different sample types
# lower sample types get a higher score to give figure a right-aligned nested structure
alt_ak_rank_scores <- apply(alt_ak_nest_mat, MARGIN=2, function(x) sum(x * rev(seq_along(x))))

ak_composite_score <- data.table(OTU_ID = names(alt_ak_spread_scores),
                              spread_score = alt_ak_spread_scores,
                              rank_score = alt_ak_rank_scores)

ak_composite_score <- ak_composite_score[order(rank_score, spread_score)]

ak_asv_order <- ak_composite_score$OTU_ID

alt_ak_nest_mat <- alt_ak_nest_mat[, ak_asv_order]

alt_ak_nest <- heatmap(alt_ak_nest_mat, Colv=NA, Rowv=NA, labCol=NA, margins = c(5,5))


```







