---
title: "Rarefy"
output: html_notebook
---

## Goal
Make smaller phyloseq objects based on sample type and merge by plot so the root objects can be rarefied.

```{r}

library(dplyr)
library(tibble)

```


## Add NewSampleType Column

```{r}

# Make data frame from sample data
sd_df <- as.data.frame(as(sample_data(unrarefied_physeq), "data.frame"))

# Change the value in new column NewSampleType according to existing values for SampleType and host. All right hand side must be same type, so NA_character_ must be used, not just NA
sd_df <- sd_df %>% 
  rownames_to_column('sampleid') %>%
  
  mutate(NewSampleType = case_when(
  (SampleType=="roots" & host=="Acacia koa") ~ "Koa root",
  (SampleType=="roots" & host=="Cheirodendron trigynum") ~ "Olapa root",
  (SampleType=="roots" & host=="Coprosma rhynchocarpa") ~ "Pilo root",
  (SampleType=="roots" & host=="Myrsine lessertiana") ~ "Kolea root",
  (SampleType=="roots" & host=="Rubus hawaiiensis") ~ "Akala root",
  (SampleType=="roots" & host=="Metrosideros polymorpha") ~ "Ohia root",
  (SampleType=="roots" & host=="Grass") ~ "Grass root",
  (SampleType=="soil") ~ "Soil",
  TRUE ~ NA_character_)) %>% column_to_rownames('sampleid')


sample_data(unrarefied_physeq)$NewSampleType <- sample_data(sd_df)$NewSampleType

```



## Short method attempt that's not working

```{r}

# Failed function
#subset_and_prune <- function(physeq, sample_type) {
Subset samples by provided sample type (Soil, Koa root, etc.)
  subset_physeq <- subset_samples(physeq, NewSampleType==as.character(sample_type))
  # Remove empty taxa
  subset_physeq <- prune_taxa(taxa_sums(subset_physeq) > 0, subset_physeq)
  return(subset_physeq)
}

#subset_func_test <- subset_and_prune(unrarefied_physeq,"Soil")


```

# Long method

## Subset samples

```{r}

## Make soil phyloseq object

# Isolate all samples per sample type. Makes a new phyloseq object with less samples
soil_samples <- subset_samples(unrarefied_physeq, NewSampleType=="Soil")

koa_root_samples <- subset_samples(unrarefied_physeq, NewSampleType=="Koa root")

ohia_root_samples <- subset_samples(unrarefied_physeq, NewSampleType=="Ohia root")

olapa_root_samples <- subset_samples(unrarefied_physeq, NewSampleType=="Olapa root")

kolea_root_samples <- subset_samples(unrarefied_physeq, NewSampleType=="Kolea root")

akala_root_samples <- subset_samples(unrarefied_physeq, NewSampleType=="Akala root")

pilo_root_samples <- subset_samples(unrarefied_physeq, NewSampleType=="Pilo root")

grass_root_samples <- subset_samples(unrarefied_physeq, NewSampleType=="Grass root")





# Remove empty taxa
soil_physeq <- prune_taxa(taxa_sums(soil_samples) > 0, soil_samples)

koa_physeq <- prune_taxa(taxa_sums(koa_root_samples) > 0, koa_root_samples)

ohia_physeq <- prune_taxa(taxa_sums(ohia_root_samples) > 0, ohia_root_samples)

olapa_physeq <- prune_taxa(taxa_sums(olapa_root_samples) > 0, olapa_root_samples)

kolea_physeq <- prune_taxa(taxa_sums(kolea_root_samples) > 0, kolea_root_samples)

akala_physeq <- prune_taxa(taxa_sums(akala_root_samples) > 0, akala_root_samples)

pilo_physeq <- prune_taxa(taxa_sums(pilo_root_samples) > 0, pilo_root_samples)

grass_physeq <- prune_taxa(taxa_sums(grass_root_samples) > 0, grass_root_samples)


# Function did not prune taxa
prune_and_merge <- function(physeq, group) {
  require(phyloseq)
  pruned_physeq <- prune_taxa(taxa_sums(physeq) > 0, physeq)
  merged_physeq <- merge_samples(physeq, group)
  return(merged_physeq)
}

#merged_soil_physeq <- prune_and_merge(soil_samples, "Plot")





```


## Merge samples by plot

```{r}

# Merge samples by plot
merged_soil_plot <- merge_samples(soil_physeq, "Plot")

merged_koa_plot <- merge_samples(koa_physeq, "Plot")

merged_ohia_plot <- merge_samples(ohia_physeq, "Plot")

merged_olapa_plot <- merge_samples(olapa_physeq, "Plot")

merged_kolea_plot <- merge_samples(kolea_physeq, "Plot")

merged_akala_plot <- merge_samples(akala_physeq, "Plot")

merged_pilo_plot <- merge_samples(pilo_physeq, "Plot")

merged_grass_plot <- merge_samples(grass_physeq, "Plot")

```


## Find lowest plot sum for root samples

```{r}

# View sequence sums per plot
# Ohia had the lowest number, so that is what was used to rarefy both root sets

# min koa = 25008
koa_rowsums <- rowSums(otu_table(merged_koa_plot))

# min ohia = 11258
ohia_rowsums <- rowSums(otu_table(merged_ohia_plot))

# min olapa = 12601
olapa_rowsums <- rowSums(otu_table(merged_olapa_plot))

# min kolea = 6848
kolea_rowsums <- rowSums(otu_table(merged_kolea_plot))

# min akala = 24074
akala_rowsums <- rowSums(otu_table(merged_akala_plot))

# min pilo = 21043
pilo_rowsums <- rowSums(otu_table(merged_pilo_plot))

# min grass = 15042
grass_rowsums <- rowSums(otu_table(merged_grass_plot))


```



```{r}

# Remove 2 plots from kolea (> 10000)
plots_to_remove <- c("AK2", "RO6")

trimmed_kolea_plot <- subset_samples(merged_kolea_plot, !(sample_names(merged_kolea_plot) %in% plots_to_remove))

trimmed_kolea_plot <- prune_taxa(taxa_sums(trimmed_kolea_plot) > 0, trimmed_kolea_plot)

trimmed_kolea_rowsums <- rowSums(otu_table(trimmed_kolea_plot))

hist(c(koa_rowsums, ohia_rowsums, olapa_rowsums, akala_rowsums, pilo_rowsums, trimmed_kolea_rowsums), breaks=50)

min(c(koa_rowsums, ohia_rowsums, olapa_rowsums, akala_rowsums, pilo_rowsums, trimmed_kolea_rowsums)) 

```




## Rarefy!

```{r}

rarefied_koa <- rarefy_even_depth(merged_koa_plot, sample.size=min(sample_sums(merged_ohia_plot)), rngseed=1)

rarefied_ohia <- rarefy_even_depth(merged_ohia_plot, sample.size=min(sample_sums(merged_ohia_plot)), rngseed=2)

rarefied_olapa <- rarefy_even_depth(merged_olapa_plot, sample.size=min(sample_sums(merged_ohia_plot)), rngseed=3)

rarefied_kolea <- rarefy_even_depth(merged_kolea_plot, sample.size=min(sample_sums(merged_ohia_plot)), rngseed=4)

rarefied_akala <- rarefy_even_depth(merged_akala_plot, sample.size=min(sample_sums(merged_ohia_plot)), rngseed=5)

rarefied_pilo <- rarefy_even_depth(merged_pilo_plot, sample.size=min(sample_sums(merged_ohia_plot)), rngseed=6)

rarefied_grass <- rarefy_even_depth(merged_grass_plot, sample.size=min(sample_sums(merged_grass_plot)), rngseed=7)

```





```{r}

# From previous koa ohia only analysis. 
# Rarefy using the lowest root plot sum. Use rngseed to reproduce in the future.

#rarefied_koa_root <- rarefy_even_depth(merged_koa_root_plot, sample.size=min(sample_sums(merged_ohia_root_plot)), rngseed=12)


#rarefied_ohia_root <- rarefy_even_depth(merged_ohia_root_plot, sample.size=min(sample_sums(merged_ohia_root_plot)), rngseed=13)

```









