---
title: "ro_bar_unique"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data frame things

```{r}

# new name so I don't mess up the old one
ro_bar_df <- ro_skookag_mat

# convert tax_table to data frame
ro_tax_table_df <- as.data.frame(tax_table(unrarefied_physeq))

# make asv rownames into column
ro_tax_table_df <- ro_tax_table_df %>% rownames_to_column('ASV')

# where family = Paraglomerales, change to Glomeromycotina
ro_tax_table_df$Family <- gsub("Paraglomerales", "Glomeromycotina", ro_tax_table_df$Family)


```



## Unique Kolea

```{r}

# isolate asvs unique to chosen host
ro_unique_kolea_asvs <- rownames(ro_bar_df)[ro_bar_df$`Kolea root`!=0 &
                                            ro_bar_df$`Grass root`==0 &
                                            ro_bar_df$`Koa root`==0 &
                                            ro_bar_df$`Akala root`==0 &
                                            ro_bar_df$`Ohia root`==0 &
                                            ro_bar_df$`Olapa root`==0 &
                                            ro_bar_df$Soil==0]

# make new ro df with only unique host asvs
ro_unique_kolea_df <- ro_bar_df[rownames(ro_bar_df) %in% ro_unique_kolea_asvs,]

# make asv rownames into a column
ro_unique_kolea_df <- ro_unique_kolea_df %>% rownames_to_column('ASV')

# make a new df with asv names and host sample asv counts as columns
ro_kolea_only_df <- ro_unique_kolea_df %>% select(ASV, `Kolea root`)

# take sum of all unique host sample sequences
ro_kolea_sum <- sum(ro_bar_df$`Kolea root`)

# make new relative abundance column by dividing unique count by total
ro_kolea_only_df <- ro_kolea_only_df %>% mutate(rel_abun = ((`Kolea root` / ro_kolea_sum) * 100))

# make new column troing family from tax_table where asv names match in both dfs
ro_kolea_only_df$family <- ro_tax_table_df$Family[match(ro_kolea_only_df$ASV, ro_tax_table_df$ASV)]

# make new column with host name filling all cells
ro_kolea_only_df$Sample <- rep("Kolea root", nrow(ro_kolea_only_df))

# change host colname for future rbind
colnames(ro_kolea_only_df)[2] <- "Count"


```


## Unique grass

```{r}

# isolate asvs unique to chosen host
ro_unique_grass_asvs <- rownames(ro_bar_df)[ro_bar_df$`Kolea root`==0 &
                                            ro_bar_df$`Grass root`!=0 &
                                            ro_bar_df$`Koa root`==0 &
                                            ro_bar_df$`Akala root`==0 &
                                            ro_bar_df$`Ohia root`==0 &
                                            ro_bar_df$`Olapa root`==0 &
                                            ro_bar_df$Soil==0]

# make new ro df with only unique host asvs
ro_unique_grass_df <- ro_bar_df[rownames(ro_bar_df) %in% ro_unique_grass_asvs,]

# make asv rownames into a column
ro_unique_grass_df <- ro_unique_grass_df %>% rownames_to_column('ASV')

# make a new df with asv names and host sample asv counts as columns
ro_grass_only_df <- ro_unique_grass_df %>% select(ASV, `Grass root`)

# take sum of all unique host sample sequences
ro_grass_sum <- sum(ro_bar_df$`Grass root`)

# make new relative abundance column by dividing unique count by total
ro_grass_only_df <- ro_grass_only_df %>% mutate(rel_abun = ((`Grass root` / ro_grass_sum) * 100))

# make new column troing family from tax_table where asv names match in both dfs
ro_grass_only_df$family <- ro_tax_table_df$Family[match(ro_grass_only_df$ASV, ro_tax_table_df$ASV)]

# make new column with host name filling all cells
ro_grass_only_df$Sample <- rep("Grass root", nrow(ro_grass_only_df))

# change host colname for future rbind
colnames(ro_grass_only_df)[2] <- "Count"

```


## Unique koa

```{r}

# isolate asvs unique to chosen host
ro_unique_koa_asvs <- rownames(ro_bar_df)[ro_bar_df$`Kolea root`==0 &
                                            ro_bar_df$`Grass root`==0 &
                                            ro_bar_df$`Koa root`!=0 &
                                            ro_bar_df$`Akala root`==0 &
                                            ro_bar_df$`Ohia root`==0 &
                                            ro_bar_df$`Olapa root`==0 &
                                            ro_bar_df$Soil==0]

# make new ro df with only unique host asvs
ro_unique_koa_df <- ro_bar_df[rownames(ro_bar_df) %in% ro_unique_koa_asvs,]

# make asv rownames into a column
ro_unique_koa_df <- ro_unique_koa_df %>% rownames_to_column('ASV')

# make a new df with asv names and host sample asv counts as columns
ro_koa_only_df <- ro_unique_koa_df %>% select(ASV, `Koa root`)

# take sum of all unique host sample sequences
ro_koa_sum <- sum(ro_bar_df$`Koa root`)

# make new relative abundance column by dividing unique count by total
ro_koa_only_df <- ro_koa_only_df %>% mutate(rel_abun = ((`Koa root` / ro_koa_sum) * 100))

# make new column troing family from tax_table where asv names match in both dfs
ro_koa_only_df$family <- ro_tax_table_df$Family[match(ro_koa_only_df$ASV, ro_tax_table_df$ASV)]

# make new column with host name filling all cells
ro_koa_only_df$Sample <- rep("Koa root", nrow(ro_koa_only_df))

# change host colname for future rbind
colnames(ro_koa_only_df)[2] <- "Count"


```


## Unique akala

```{r}

# isolate asvs unique to chosen host
ro_unique_akala_asvs <- rownames(ro_bar_df)[ro_bar_df$`Kolea root`==0 &
                                            ro_bar_df$`Grass root`==0 &
                                            ro_bar_df$`Koa root`==0 &
                                            ro_bar_df$`Akala root`!=0 &
                                            ro_bar_df$`Ohia root`==0 &
                                            ro_bar_df$`Olapa root`==0 &
                                            ro_bar_df$Soil==0]

# make new ro df with only unique host asvs
ro_unique_akala_df <- ro_bar_df[rownames(ro_bar_df) %in% ro_unique_akala_asvs,]

# make asv rownames into a column
ro_unique_akala_df <- ro_unique_akala_df %>% rownames_to_column('ASV')

# make a new df with asv names and host sample asv counts as columns
ro_akala_only_df <- ro_unique_akala_df %>% select(ASV, `Akala root`)

# take sum of all unique host sample sequences
ro_akala_sum <- sum(ro_bar_df$`Akala root`)

# make new relative abundance column by dividing unique count by total
ro_akala_only_df <- ro_akala_only_df %>% mutate(rel_abun = ((`Akala root` / ro_akala_sum) * 100))

# make new column troing family from tax_table where asv names match in both dfs
ro_akala_only_df$family <- ro_tax_table_df$Family[match(ro_akala_only_df$ASV, ro_tax_table_df$ASV)]

# make new column with host name filling all cells
ro_akala_only_df$Sample <- rep("Akala root", nrow(ro_akala_only_df))

# change host colname for future rbind
colnames(ro_akala_only_df)[2] <- "Count"

```


## Unique ohia

```{r}

# isolate asvs unique to chosen host
ro_unique_ohia_asvs <- rownames(ro_bar_df)[ro_bar_df$`Kolea root`==0 &
                                            ro_bar_df$`Grass root`==0 &
                                            ro_bar_df$`Koa root`==0 &
                                            ro_bar_df$`Akala root`==0 &
                                            ro_bar_df$`Ohia root`!=0 &
                                            ro_bar_df$`Olapa root`==0 &
                                            ro_bar_df$Soil==0]

# make new ro df with only unique host asvs
ro_unique_ohia_df <- ro_bar_df[rownames(ro_bar_df) %in% ro_unique_ohia_asvs,]

# make asv rownames into a column
ro_unique_ohia_df <- ro_unique_ohia_df %>% rownames_to_column('ASV')

# make a new df with asv names and host sample asv counts as columns
ro_ohia_only_df <- ro_unique_ohia_df %>% select(ASV, `Ohia root`)

# take sum of all unique host sample sequences
ro_ohia_sum <- sum(ro_bar_df$`Ohia root`)

# make new relative abundance column by dividing unique count by total
ro_ohia_only_df <- ro_ohia_only_df %>% mutate(rel_abun = ((`Ohia root` / ro_ohia_sum) * 100))

# make new column troing family from tax_table where asv names match in both dfs
ro_ohia_only_df$family <- ro_tax_table_df$Family[match(ro_ohia_only_df$ASV, ro_tax_table_df$ASV)]

# make new column with host name filling all cells
ro_ohia_only_df$Sample <- rep("Ohia root", nrow(ro_ohia_only_df))

# change host colname for future rbind
colnames(ro_ohia_only_df)[2] <- "Count"

```


## Unique olapa

```{r}

# isolate asvs unique to chosen host
ro_unique_olapa_asvs <- rownames(ro_bar_df)[ro_bar_df$`Kolea root`==0 &
                                            ro_bar_df$`Grass root`==0 &
                                            ro_bar_df$`Koa root`==0 &
                                            ro_bar_df$`Akala root`==0 &
                                            ro_bar_df$`Ohia root`==0 &
                                            ro_bar_df$`Olapa root`!=0 &
                                            ro_bar_df$Soil==0]

# make new ro df with only unique host asvs
ro_unique_olapa_df <- ro_bar_df[rownames(ro_bar_df) %in% ro_unique_olapa_asvs,]

# make asv rownames into a column
ro_unique_olapa_df <- ro_unique_olapa_df %>% rownames_to_column('ASV')

# make a new df with asv names and host sample asv counts as columns
ro_olapa_only_df <- ro_unique_olapa_df %>% select(ASV, `Olapa root`)

# take sum of all unique host sample sequences
ro_olapa_sum <- sum(ro_bar_df$`Olapa root`)

# make new relative abundance column by dividing unique count by total
ro_olapa_only_df <- ro_olapa_only_df %>% mutate(rel_abun = ((`Olapa root` / ro_olapa_sum) * 100))

# make new column troing family from tax_table where asv names match in both dfs
ro_olapa_only_df$family <- ro_tax_table_df$Family[match(ro_olapa_only_df$ASV, ro_tax_table_df$ASV)]

# make new column with host name filling all cells
ro_olapa_only_df$Sample <- rep("Olapa root", nrow(ro_olapa_only_df))

# change host colname for future rbind
colnames(ro_olapa_only_df)[2] <- "Count"

```


## Unique soil

```{r}

# isolate asvs unique to chosen host
ro_unique_soil_asvs <- rownames(ro_bar_df)[ro_bar_df$`Kolea root`==0 &
                                            ro_bar_df$`Grass root`==0 &
                                            ro_bar_df$`Koa root`==0 &
                                            ro_bar_df$`Akala root`==0 &
                                            ro_bar_df$`Ohia root`==0 &
                                            ro_bar_df$`Olapa root`==0 &
                                            ro_bar_df$Soil!=0]

# make new ro df with only unique host asvs
ro_unique_soil_df <- ro_bar_df[rownames(ro_bar_df) %in% ro_unique_soil_asvs,]

# make asv rownames into a column
ro_unique_soil_df <- ro_unique_soil_df %>% rownames_to_column('ASV')

# make a new df with asv names and host sample asv counts as columns
ro_soil_only_df <- ro_unique_soil_df %>% select(ASV, `Soil`)

# take sum of all unique host sample sequences
ro_soil_sum <- sum(ro_bar_df$`Soil`)

# make new relative abundance column by dividing unique count by total
ro_soil_only_df <- ro_soil_only_df %>% mutate(rel_abun = ((`Soil` / ro_soil_sum) * 100))

# make new column troing family from tax_table where asv names match in both dfs
ro_soil_only_df$family <- ro_tax_table_df$Family[match(ro_soil_only_df$ASV, ro_tax_table_df$ASV)]

# make new column with host name filling all cells
ro_soil_only_df$Sample <- rep("Soil", nrow(ro_soil_only_df))

# change host colname for future rbind
colnames(ro_soil_only_df)[2] <- "Count"

```




## rbind

```{r}

ro_total_rbind <- do.call("rbind", list(ro_kolea_only_df,
                                        ro_grass_only_df,
                                        ro_koa_only_df,
                                        ro_akala_only_df,
                                        ro_ohia_only_df,
                                        ro_olapa_only_df,
                                        ro_soil_only_df))

ro_total_rbind <- na.omit(ro_total_rbind)

## Getting ASV counts for bar labels

# make a copy
ro_total_rbind_sums <- ro_total_rbind

# detach plyr if using. summarise() in plyr does something different
ro_total_rbind_sums <- ro_total_rbind_sums %>% group_by(Sample) %>% summarise(count=length(unique(ASV)), abund=sum(rel_abun))


```
## Plot

```{r}

ro_unique_bar <- ggplot(ro_total_rbind, aes(x=Sample, fill=family, y=rel_abun)) +
  geom_bar(stat="identity", position="stack") +
  theme(axis.text.x = element_text(angle=90, size=14, colour="black", vjust=0.5, hjust=1, face="bold"), panel.grid.major=element_blank(), panel.grid.minor=element_blank(), panel.background=element_blank(),
        axis.line = element_line(colour="gray"),
        axis.title.y = element_text(size=16, face="bold"),
        legend.title = element_text(size=16, face="bold"),
        legend.text = element_text(size=12, face="bold", colour="black"),
        axis.text.y = element_text(colour="black", size=12, face="bold")) +
  ylim(0,10) +
  theme(plot.margin = unit(c(1,1,1,1), "cm")) +
  labs(x = "", y = "Relative Abundance (%)", fill="Family") +
  scale_fill_brewer(palette = "Spectral") +
  geom_text(data=ro_total_rbind_sums, aes(x=Sample, y=abund, label=count), inherit.aes = F, vjust=-1)

```






