---
title: "ro_split"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## AK Restored

```{r}

ro_soil <- subset_samples(merged_soil_plot, grepl("RO", sample_names(merged_soil_plot)))
ro_soil <- prune_taxa(taxa_sums(ro_soil) > 0, ro_soil)

ro_koa <- subset_samples(rarefied_koa, grepl("RO", sample_names(rarefied_koa)))
ro_koa <- prune_taxa(taxa_sums(ro_koa) > 0, ro_koa)

ro_kolea <- subset_samples(rarefied_kolea, grepl("RO", sample_names(rarefied_kolea)))
ro_kolea <- prune_taxa(taxa_sums(ro_kolea) > 0, ro_kolea)

ro_ohia <- subset_samples(rarefied_ohia, grepl("RO", sample_names(rarefied_ohia)))
ro_ohia <- prune_taxa(taxa_sums(ro_ohia) > 0, ro_ohia)

ro_olapa <- subset_samples(rarefied_olapa, grepl("RO", sample_names(rarefied_olapa)))
ro_olapa <- prune_taxa(taxa_sums(ro_olapa) > 0, ro_olapa)

ro_akala <- subset_samples(rarefied_akala, grepl("RO", sample_names(rarefied_akala)))
ro_akala <- prune_taxa(taxa_sums(ro_akala) > 0, ro_akala)

#ro_pilo <- subset_samples(rarefied_pilo, grepl("RO", sample_names(rarefied_pilo)))
#ro_pilo <- prune_taxa(taxa_sums(ro_pilo) > 0, ro_pilo)

ro_grass <- subset_samples(rarefied_grass, grepl("RO", sample_names(rarefied_grass)))
ro_grass <- prune_taxa(taxa_sums(ro_grass) > 0, ro_grass)



```


```{r}

ro_soil_mat <- make_matrix(ro_soil)
ro_koa_mat <- make_matrix(ro_koa)
ro_kolea_mat <- make_matrix(ro_kolea)
ro_ohia_mat <- make_matrix(ro_ohia)
ro_olapa_mat <- make_matrix(ro_olapa)
ro_akala_mat <- make_matrix(ro_akala)
#ro_pilo_mat <- make_matrix(ro_pilo)
ro_grass_mat <- make_matrix(ro_grass)


```


```{r}

# Change the column name
colnames(ro_soil_mat) <- c("Soil")

colnames(ro_koa_mat) <- c("Koa root")

colnames(ro_ohia_mat) <- c("Ohia root")

colnames(ro_olapa_mat) <- c("Olapa root")

colnames(ro_kolea_mat) <- c("Kolea root")

colnames(ro_akala_mat) <- c("Akala root")

#colnames(ro_pilo_mat) <- c("Pilo root")

colnames(ro_grass_mat) <- c("Grass root")

```


```{r}

# merge 2 matrices by row names
# all=TRUE adds extra columns or rows with an NA where there is no matching value
# The result is a 3 column matrix with the first column as all the ASV names
ro_sk_mat <- merge(ro_soil_mat, ro_koa_mat, by="row.names", all=TRUE)

# Takes ASV names from column 1 and names rows after them 
rownames(ro_sk_mat) <- ro_sk_mat[,1]

# Removes column 1 with ASV names
ro_sk_mat[,1] <- NULL

#Add ohia
ro_sko_mat <- merge(ro_sk_mat, ro_ohia_mat, by="row.names", all=T)
rownames(ro_sko_mat) <- ro_sko_mat[,1]
ro_sko_mat[,1] <- NULL

#Add olapa
ro_skoo_mat <- merge(ro_sko_mat, ro_olapa_mat, by="row.names", all=T)
rownames(ro_skoo_mat) <- ro_skoo_mat[,1]
ro_skoo_mat[,1] <- NULL

#Add kolea
ro_skook_mat <- merge(ro_skoo_mat, ro_kolea_mat, by="row.names", all=T)
rownames(ro_skook_mat) <- ro_skook_mat[,1]
ro_skook_mat[,1] <- NULL

#Add akala
ro_skooka_mat <- merge(ro_skook_mat, ro_akala_mat, by="row.names", all=T)
rownames(ro_skooka_mat) <- ro_skooka_mat[,1]
ro_skooka_mat[,1] <- NULL

#Add pilo
#ro_skookap_mat <- merge(ro_skooka_mat, ro_pilo_mat, by="row.names", all=T)
#rownames(ro_skookap_mat) <- ro_skookap_mat[,1]
#ro_skookap_mat[,1] <- NULL

#Add grass
ro_skookag_mat <- merge(ro_skooka_mat, ro_grass_mat, by="row.names", all=T)
rownames(ro_skookag_mat) <- ro_skookag_mat[,1]
ro_skookag_mat[,1] <- NULL



#ro_skookapg_mat$`Pilo root` <- NULL
#ro_skookag_mat <- ro_skookapg_mat

# Changes NAs to 0
ro_skookag_mat[is.na(ro_skookag_mat)] <- 0


```



```{r}

ro_skookag_mat_pa <- ro_skookag_mat

# Makes presence absence (turns any value > 0 into 1)
ro_skookag_mat_pa[ro_skookag_mat_pa > 0] <- 1

```


```{r}

ak_mat <- ak_skookap_mat

ro_mat <- ro_skookap_mat

```



```{r}

ro_skookap_euler <- euler(ro_skookap_mat)
ro_skookap_euler_plot <- plot(ro_skookap_euler, fills=TRUE, quantities=TRUE)
ro_skookap_euler_plot

```



```{r}
ro_skookag_mat_pa <- ro_skookag_mat

# Changes NAs to 0
ro_skookag_mat_pa[is.na(ro_skookag_mat_pa)] <- 0

# Makes presence absence (turns any value > 0 into 1)
ro_skookag_mat_pa[ro_skookag_mat_pa > 0] <- 1


upset(ro_skookag_mat_pa, nsets=7, nintersects = NA, sets.x.label = "Total ASVs")


```

## Upset with Percentages

```{r}

# make a copy of presence absence matrix
ro_skookag_boo <- ro_skookag_mat_pa

# convert binary to boolean
ro_skookag_boo <- apply(ro_skookag_boo, 2, function(x) as.logical(x))

# convert matrix to data frame
ro_skookag_boo <- as.data.frame(ro_skookag_boo)

# extract col names to feed into upset
ro_skookag_hosts <- colnames(ro_skookag_boo)


# generate upset plot with percentage labels
upset(
  ro_skookag_boo, 
  ro_skookag_hosts, 
  name = '',
  min_size=1,
  width_ratio = 0.1,
  base_annotations = list(
    'Intersection size'=intersection_size(
      text=list(size=3, angle=60, vjust=-0.1, hjust=-0.1), 
      text_aes = aes(
      label=paste0(signif(intersection_size/nrow(ro_skookag_boo) * 100, digits=2), '%')))), 
  themes = upset_modify_themes(
    list(
      'Intersection_size'=theme(
        panel.grid.major=element_blank(), 
        panel.grid.minor=element_blank())
      )
    )
  )


```




## RO Nestedness

```{r}

# Convert data frame to matrix
ro_skookag_mat_nest <- as(ro_skookag_mat_pa, "matrix")


sort(colSums(ro_skookag_mat_nest))

# Tranpose matrix (flip axes)
ro_skookag_mat_nest <- t(ro_skookag_mat_nest)


ro_sample_order <- c("Soil",
                     "Kolea root",
                     "Grass root",
                     "Koa root",
                    "Akala root",
                    "Ohia root",
                    "Olapa root")

alt_ro_sample_order <- c("Soil",
                     "Koa root",
                     "Akala root",
                     "Grass root",
                    "Kolea root",
                    "Ohia root",
                    "Olapa root")

ro_nest_mat <- ro_skookag_mat_nest[alt_ro_sample_order,]



# count how many samples each ASV is in
ro_spread_scores <- colSums(ro_nest_mat)

# assign each ASV a weighted score based on its presence in different sample types
# lower sample types get a higher score to give figure a right-aligned nested structure
ro_rank_scores <- apply(ro_nest_mat, MARGIN=2, function(x) sum(x * rev(seq_along(x))))

ro_composite_score <- data.table(OTU_ID = names(ro_spread_scores),
                              spread_score = ro_spread_scores,
                              rank_score = ro_rank_scores)

ro_composite_score <- ro_composite_score[order(rank_score, spread_score)]

ro_asv_order <- ro_composite_score$OTU_ID

ro_nest_mat <- ro_nest_mat[, ro_asv_order]

ro_nest <- heatmap(ro_nest_mat, Colv=NA, Rowv=NA, labCol=NA, margins = c(5,5))


```





